### PR TITLE
adding automatic handling for blank spaces in rolls

### LINKED ISSUE #9: When missformatting the roll by adding spaces, app errors
Running this in a docker container and when testing I found that when entering the roll incorrectly by adding a space (ie. '2d6 +2') the bot would outright crash.

I'm pretty novice at Python but have created a fork and will try to see if I can fix this, I figure a validation of the entry before running it will fix sort this.

Here's the error Im getting when it crashes:

```
/eon-bot

File app/main.py exists.

Starting app/main.py.

Logged in as EON-Bot#6811

Latency is 0.09995200112462044

Activity is playing: with cosmic demons

Debug is True

debug_guilds is None

Regex Debug

Regex NOT matched

cannot unpack non-iterable NoneType object

Bad Roll Debug

Ignoring exception in command ob:

Traceback (most recent call last):

  File "/eon-bot/app/modules/functions.py", line 135, in rollInfiniteDice

    number_of_rolls, sides_to_die, bonus = splitRollString(

TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/commands/core.py", line 124, in wrapped

    ret = await coro(arg)

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/commands/core.py", line 980, in _invoke

    await self.callback(ctx, **kwargs)

  File "/eon-bot/app/main.py", line 133, in ob

    results = rollInfiniteDice(ob_roll, debug)

  File "/eon-bot/app/modules/functions.py", line 163, in rollInfiniteDice

    print(sum_rolls)

UnboundLocalError: local variable 'sum_rolls' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/bot.py", line 1114, in invoke_application_command

    await ctx.command.invoke(ctx)

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/commands/core.py", line 375, in invoke

    await injected(ctx)

  File "/eon-bot/venv/lib/python3.10/site-packages/discord/commands/core.py", line 132, in wrapped

    raise ApplicationCommandInvokeError(exc) from exc

discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: UnboundLocalError: local variable 'sum_rolls' referenced before assignment

```

### PR DESCRIPTION
**Pull request by nagarutu**
closes #9

### CODE REVIEW

**Comment by nagarutu** [comment]
Also applied fix to rollForFight function

**Comment by obgr** [comment]
It makes sense to also make sure to implement this for regular rolls, and queued rolls.
Would you mind to look over that as well? :)

**Comment by nagarutu** [comment]
Sure I’ll give it a whirl

**Comment by nagarutu** [comment]
Sorry for the spams on Commits to main :)
Its now updated with handling for regular rolls and for ob rolls, this also works when using /qr,
Also when dealing with Rolls on /qr I found that a /n was missing to make new rolls appear on new rows so I added that as well.

**Comment by obgr** [comment]
Looks good, thanks!

BR Olle

**Pull request merged**
